let inputWidth= prompt("Enter the width");
let inputHeight= prompt("Enter the height");
let width= parseInt(inputWidth);
   document.write('Enter width: ' + width);
   document.write("<br/>");
let height= parseInt(inputHeight);
   document.write('Enter height: ' + height);
   document.write("<br/>");
let area= width * height;
   document.write("The area is: " + area);
